[package]
name = "galaga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.1"
bevy_asset_loader = { version = "0.21.0", features = ["2d"] }
bevy_ggrs = "0.16.0"
